baseurl: https://cerulean-cactus-9432fc.netlify.app/
title: Museum of Art and Numbers
theme: newsroom
author: Weru
copyright: Copyright © 2019, Weru and the Hugo Authors; all rights reserved.
canonifyurls: yes
paginate: 100
markup:
  goldmark:
    renderer:
      hardWraps: no
      unsafe: no
      xhtml: no
  highlight:
    codeFences: yes
    guessSyntax: no
    hl_Lines: ''
    lineNoStart: 1
    lineNos: yes
    lineNumbersInTable: no
    noClasses: no
    tabWidth: 2
params: {}
